### ISSUE TITLE
Can I use different option properties as names and values?

### ISSUE THREAD

**Issue by airandfingers** [amitava82/angular-multiselect#26]
Per the example at http://plnkr.co/edit/LPGYIf?p=preview, I'm using one property of my option objects as the name for the option, with options="t.name for t in tags".

Rather than use the entire option object as a value, I want to only use the _id property, so that the model I bind to contains a list of _id Strings, rather than a list of Objects. This matches my backend, where my MongoDB documents have _id references to other documents.

Is it possible to use a single property as the value of an option, e.g. values="t._id for t in tags"?

My code is live at http://trollsgoals.ayoshitake.com/

**Comment by RobbertWolfs** [comment]
@airandfingers Is your pull request accepted? Because I think we have the same problem, we also want the model we bind to contains a list of id strings.. We are also trying to use "t._id as t.name for t in tags" but it always binds our full model to the list.

**Comment by amitava82** [comment]
I'm going to look into this tomorrow and make necessary changes 👍

**Comment by RobbertWolfs** [comment]
That would be awesome 👍

**Comment by amitava82** [comment]
@RobbertWolfs So, I just tried `c.id as c.name for c in fruits` and it binds `id` to the selected.  Can you show me an example in plunk?

http://plnkr.co/edit/NKas7sSP5lGJz3OTv0YU?p=preview

**Comment by RobbertWolfs** [comment]
@amitava82 Let me try to implement it as your example. Otherwise I will try to create a plunker.

**Comment by RobbertWolfs** [comment]
Could it be it gives problems with angular 1.5.5? Because we are using the angular components from angular 1.5.x... 

I tried to create a gist of all the necessary code https://gist.github.com/RobbertWolfs/4c03ff1a27b042d3fb1d97c1b86445d7

And this is the result we get...

<img width="580" alt="screen shot 2016-06-07 at 10 54 53" src="https://cloud.githubusercontent.com/assets/12511178/15851735/57bd759a-2c9e-11e6-8e98-b5d5b7c1091a.png">

**Comment by amitava82** [comment]
Are you sure that you are using latest version of multiselect lib?

**Comment by RobbertWolfs** [comment]
I just did npm install angular-multiselect

**Comment by amitava82** [comment]
ah.. It's old.. Hold on, I'll push latest.

**Comment by RobbertWolfs** [comment]
ok thanks

**Comment by amitava82** [comment]
Alright published `angular-multiselect@1.2.0`

**Comment by RobbertWolfs** [comment]
Let me check if I get it to work with the new version.

**Comment by RobbertWolfs** [comment]
@amitava82 Thank you it works like a charm 👍 💯
