### ISSUE TITLE
Not supported in IE

### ISSUE THREAD

**Issue by pc-zhang** [amitava82/angular-multiselect#41]
'restrict E' is not supported in IE, 'restrict A' better

**Comment by zachlysobey** [comment]
Correct me if I'm wrong, but this is only IE <= 8. Many (most?) of us don't have to worry about browsers that old anymore, and [Angular >=1.3 no longer supports it](https://docs.angularjs.org/guide/ie)

**Comment by zachlysobey** [comment]
If anything, user 'restrict AE' to allow both ways. (or leave blank as this is the default)

**Comment by zachlysobey** [comment]
what do you think @amitava82. My vote is close this as a `wontfix`.

**Comment by amitava82** [comment]
Is this issue with IE 8 and below? If so, then really don't care. :skull:
