### ISSUE TITLE
Obsolete examples

### ISSUE THREAD

**Issue by lucasmoglia** [amitava82/angular-multiselect#52]
Hi! I just want to notice you about your example code, because it is obsolete against the code published within your repository. 

With the code pulled from your repo, i couldn't get the selected object (complete (id & name)), because the tool was just mapping the name from the select list.

Example: 

if i have this array: [{id:1, name: 'Audi'}, {id:2, name: 'BMW'}, {id:1, name: 'Honda'}] and i select the first option on the dropdown...it shows:

['Honda']

You can see this example here: http://plnkr.co/edit/BBJWIY?p=preview

After a while I copied the entire code from your plunker example file, called 'multiselec.js' and it works fine now.

Am I missing something? I mean, is there any way to get the selected object entirely ('name' and 'id' attributes) using the code published on your repository?

PD: By the way, sorry about my poor english! =/

**Comment by amitava82** [comment]
You have to use option expression they way you need your model to be. Updated doc and example.
