### ISSUE TITLE
Use a dash in directive name?

### ISSUE THREAD

**Issue by zachlysobey** [amitava82/angular-multiselect#61]
It is considered best practice to have angular directive names contain a dash. (`my-directive`). This prevents collisions with any potential html elements that may be added to the spec in the future. The W3C has stated that they will not create any html elements or attributes (aside from `data-`) that contain dashes, so custom elements can use them safely.

Perhaps `multi-select` like similar plugins use? Or maybe `ami-multiselect` would be better?

**Comment by amitava82** [comment]
Fixed.
