### ISSUE TITLE
Rename dist/style.css

### ISSUE THREAD

**Issue by zachlysobey** [amitava82/angular-multiselect#62]
I think it would be nice to rename this file to be something a bit more specific, like `multiselect.css`. This seems to be the common practice for angular libraries

In my case will prevent me from having to make changes to my build step. (it currently takes a list of css file paths and moves them into a folder named vendor.) So... for your library I will be including `vendor/style.css` which is a bit ambiguous.

**Comment by amitava82** [comment]
Yes, sounds reasonable.

**Comment by amitava82** [comment]
Fixed
