### ISSUE TITLE
multiselect-tpls.js has a syntax error

### ISSUE THREAD

**Issue by zachlysobey** [amitava82/angular-multiselect#63]
on line 27 of multiselect-tpls.js:

```javascript
.directive('multiselect',// ...
```

`.directive()` is called after a semi-colon on line 25. Resulting in:

> Uncaught SyntaxError: Unexpected token .

**Comment by zachlysobey** [comment]
Actually... what is going on here? I assumed that this file was pretty much the same as the other, but with the template inlined, but there seem to be substantial differences otherwise.

Is this file just totally out of sync? It hasn't been edited since April 2014?
https://github.com/amitava82/angular-multiselect/commits/master/src/multiselect-tpls.js

**Comment by zachlysobey** [comment]
Thanks for merging that in, but the my other question still stands.

Is it suggested to use this file anymore? It seems quite out of sync with the non-tmpl version.

Ideally these 2 files would probably be generated from the same base code in your build script... maybe I will get a chance at some point to put a PR together. Think I should open another issue for that?

**Comment by amitava82** [comment]
I was under impression that @naga2raja contributed the build system also did that.

**Comment by zachlysobey** [comment]
Just reviewd the gulpfile, and it doesn't look like it does. It is possible, though a bit involved perhaps? I've inlined template files in scripts with gulp before (with [gulp-angular-templatecache](https://www.npmjs.com/package/gulp-angular-templatecache)), but never produced 2 output files from one.

**Comment by zachlysobey** [comment]
Will create new issue

**Comment by naga2raja** [comment]
I 'm sorry to interfere here.. I just want to know what is the exact issue happening here.. Is the build not working? or there is the problem with multiselect-tpls.js?

**Comment by amitava82** [comment]
@naga2raja `multiselect-tpls.js` was not being generated on build time. @zachlysobey fixed it. Thanks for your build system :+1:

**Comment by naga2raja** [comment]
Oh!! Thanks for fix.. and sorry I didn't check properly

**Comment by zachlysobey** [comment]
@naga2raja Nice work getting the gulpfile in here in the first place. I'm open to criticism on the new stuff I added. I'm somewhat new to gulp/node/streams and am not entirely confident that I'm doing things in the most idiomatic way.

If I get a chance, maybe I'll finish wiring up some of that other stuff (linting, minification, etc..) that you got started?

It looks like I am going to make heavy use of this project in my work, and would like to continue to help contributing to make it even better.

**Comment by zachlysobey** [comment]
I should probably have referenced [this issue](https://github.com/amitava82/angular-multiselect/issues/66) and [this PR](https://github.com/amitava82/angular-multiselect/pull/67)
