### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by zachlysobey** [amitava82/angular-multiselect#65]
Sorry I submitted so many issues today. I'm really trying to get a multi-select solution in place. I've had a couple failed attempts at using [other projects I found](gist.github.com/zachlysobey/c45a2e5343c87ec9a1c5) and it looked like your project might be perfect for me.

Before I go too much further, I do want to know if you plan to actively maintain this project. I'm willing to offer some help, but if you're not really into it, I will either fork, or choose another project. I see you have labeled it a "work in progress" and there is some definite room for improvement, but I really like this project's foundation.

Please let me know what you think.

**Comment by amitava82** [comment]
This piece of directive started off from one of my project I was working on and there where no such library at that point (Angular .9 era) Though I'm not working on Angular project at this moment, I do keep checking issues, and PR. Help always welcome! Be warned, I'm out of touch with development with angular.js! I'm not sure if this works with latest version of Angular.JS. I'm glad people finding this helpful and contributing to fix issues.

**Comment by zachlysobey** [comment]
Thank you for your continued effort!
