### ISSUE TITLE
Documentation incorrect about installation

### ISSUE THREAD

**Issue by akempes** [amitava82/angular-multiselect#71]
I've tried run ```bower install angular-multiselect``` but a whole different package is added to my project...

**Comment by zachlysobey** [comment]
While this may in fact be a legit issue, I would offer the advice to kick bower to the curb if you can.

> https://twitter.com/nachocoloma/status/663622545162280960

**Comment by zachlysobey** [comment]
It checks out. [This Search](http://bower.io/search/?q=angular-multiselect) shows that the bower project is in fact *amitava82-angular-multiselect*, not *angular-multiselect*

I'll update the docs.
