### ISSUE TITLE
amitava82/angular-multiselect=amitava82-angular-multiselect is not a valid repository name

### ISSUE THREAD

**Issue by cyberz** [amitava82/angular-multiselect#80]
run:
bower install amitava82-angular-multiselect --save
all ok.

Then run bower install ... and got:
```

bower angular-multiselect=amitava82-angular-multiselect#^1.0.0          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/amitava82/angular-multiselect=amitava82-angular-multiselect.git", exit code of #128 fatal: remote error:    amitava82/angular-multiselect=amitava82-angular-multiselect is not a valid repository name   Email support@github.com for help

Additional error details:
fatal: remote error:
  amitava82/angular-multiselect=amitava82-angular-multiselect is not a valid repository name
  Email support@github.com for help
```

**Comment by amitava82** [comment]
Seems working fine for me. 
```
bower install amitava82/angular-multiselect
```
I just created a new tag release. Bower version was a year old.

**Comment by cyberz** [comment]
I try
`bower install amitava82/angular-multiselect `
package installed fine, but after I'm run 
`bower install`
and got
`bower                        ENOTFOUND Package amitava82/angular-multiselect=amitava82/angular-multiselect not found`
What I'm doing wrong ?

**Comment by xfight0** [comment]
+1, I also find the error in last version
