### ISSUE TITLE
Any scroll bar for this widget?

### ISSUE THREAD

**Issue by rahxphoon** [amitava82/angular-multiselect#81]
@amitava82 
I like your clean selection box widget. Since the options are getting larger and larger, is there a scroll bar  for me to control?

**Comment by amitava82** [comment]
You should be able to control that through css `overflow-y: auto` & `max-height`

**Comment by rahxphoon** [comment]
Thank you for your early reply, but another problem is there a scroll bar for your am-multiselect tag? The css is not working, sorry I am new to angualrJS

**Comment by amitava82** [comment]
Check this example http://plnkr.co/edit/u6cwqDHdgShNZAbjCHBR?p=preview

**Comment by rahxphoon** [comment]
My bad! Problem solved,Thanks for your kindness help!!!!!!!!
