### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by Veske** [amitava82/angular-multiselect#82]
Has anyone actually tried the disabled state? If I would put ng-disabled="someExpressionThatEvaluatesToTrue" then the multiselect will not get disabled.

The line $parse(attrs.disabled)(originalScope) seems to return undefined.

**Comment by amitava82** [comment]
It's `disabled` as you can see in `e $parse(attrs.disabled)(originalScope) `

**Comment by Veske** [comment]
Huh? ng-disabled adds a disabled property to the html element if the expression equals to true. Problem is that the line` $parse(attrs.disabled)(originalScope)` return undefined or to be more precise it returns null. So the listener function never gets called.

**Comment by Veske** [comment]
I mean go here: http://amitava82.github.io/angular-multiselect/    and try to add either disabled or ng-disabled to any of the multiselect boxes. It has no effect.
