### ISSUE TITLE
assign already selected itms list

### ISSUE THREAD

**Issue by ali-khan-confiz** [amitava82/angular-multiselect#88]
can any one please tell me that how to make it properly work able when a list of already selected attributes provided to multi select directive and then it show those items selected in UI too
Any solution would be much appreciated

**Comment by deifos** [comment]
Did you find a solution to this?

**Comment by ali-khan-confiz** [comment]
Thanks but i found a way around too at that time but [this ](https://github.com/amitava82/angular-multiselect/issues/33)solution is good too
